#!/bin/bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Get the hostname of the server
hostname=$(hostname)

# Configure Nginx to include custom HTTP response header
sudo bash -c 'cat <<EOF > /etc/nginx/conf.d/custom_http_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By $hostname;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
    }

    # Remove default Nginx server block
    include /etc/nginx/sites-enabled/*;
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx

