#!/bin/bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 427681-web-01 54.227.128.50 check
    server web-02 427681-web-02 18.208.120.192 check
EOF'

# Enable HAProxy service to be managed via init script
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

