#!/bin/usr/env bash
# Script display 'bad luck' on 4th iteration and 'good luck' ont the 8th

a="1"
while [ $a -le 10 ]
do
	if [ $a -eq 4 ]
	then
		echo "bad luck"
	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	((a++))
done
