#!/bin/usr/env bash
# Script displays "bad luck" from China 4th,Japan 9th,Italy 17th on iteration of numbers 1-20

a="1"
while [$a -le 20 ]
do
    case $a in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $a
            ;;
    esac

    ((a++))
done
